Template for RunOfOnes challenge
codeconnector/CodingDojo pull request #106
Opened 2021-06-26 14:50 UTC by parhaml

closes #91 

PLEASE please check my work.

I copied everything from a previous `java` challenge and tried to frankenstien it together. Thanks!

2021-06-27 19:13 UTC, ericwburden commented
It looks like you copied from the Intervening Verbiage setup (which is an older Java setup). I'd recommend looking at the Find Three Largest Numbers (06/01) challenge, which simplifies the setup and uses symlinks for the test script. My other recommendation would be to include a test for 0 as an edge case.

2021-06-27 19:19 UTC, ericwburden requested changes
Most of my comments are pretty much just beating a dead horse (about using a more recent Java challenge as the setup template), but do check the comments on the tests (they currently all pass with a result of `3`).

2021-06-27 19:19 UTC, ericwburden commented on challenges/2021-06-29-run-of-ones/src/test/java/io/codeconnector/codedojo/RunOfOnesTest.java
> +        assertEquals(3, result);
should be `assertEquals(4, result);`

2021-06-27 19:19 UTC, ericwburden commented on challenges/2021-06-29-run-of-ones/src/test/java/io/codeconnector/codedojo/RunOfOnesTest.java
> +        assertEquals(3, result);
should be `assertEquals(2, result);`

2021-06-27 19:19 UTC, ericwburden commented on challenges/2021-06-29-run-of-ones/src/test/java/io/codeconnector/codedojo/RunOfOnesTest.java
> +        assertEquals(3, result);
should be `assertEquals(1, result);`

2021-06-27 19:19 UTC, ericwburden commented on challenges/2021-06-29-run-of-ones/test-it.sh
> +#!/bin/bash
The newer version of this challenge setup uses a symlink to the testing script.

2021-06-27 19:19 UTC, ericwburden commented on challenges/2021-06-29-run-of-ones/src/main/java/io/codeconnector/codedojo/RunOfOnes.java
> +package io.codeconnector.codedojo;
The newer version of the Java challenge setup includes the code and tests in a single file/class.

2021-06-27 19:19 UTC, ericwburden commented on challenges/2021-06-29-run-of-ones/mob.java
> +src/main/java/io/codeconnector/codedojo/InterveningVerbiage.java
This symlink is broken.

2021-06-27 19:19 UTC, ericwburden commented on challenges/2021-06-29-run-of-ones/challenge.md
> +## Tackling This Challenge
This section includes some references to the challenge it was copied from. The updated Java setup format includes a briefer 'Tackling This Challenge' section with more generic comments.

2021-06-27 20:19 UTC, parhaml commented
> Most of my comments are pretty much just beating a dead horse (about using a more recent Java challenge as the setup template), but do check the comments on the tests (they currently all pass with a result of `3`).
Oooh. Nice catch. I did that to ensure the passing shell stuff would work and forgot to change it back.


I'll definitely look at the other set-up. Thanks!

2021-06-29 01:48 UTC, parhaml commented on challenges/2021-06-29-run-of-ones/src/test/java/io/codeconnector/codedojo/RunOfOnesTest.java
> +        assertEquals(3, result);
updated!

2021-06-29 01:48 UTC, parhaml commented on challenges/2021-06-29-run-of-ones/src/test/java/io/codeconnector/codedojo/RunOfOnesTest.java
> +        assertEquals(3, result);
updated

2021-06-29 01:54 UTC, parhaml commented
@ericwburden this has been updated

2021-06-29 02:16 UTC, ericwburden approved these changes
Looks good to me. I made one change to the comments in the RunOfOnes.java file.

2021-06-29 13:22 UTC, parhaml commented
> Looks good to me. I made one change to the comments in the RunOfOnes.java file.

Doh. Nice

2021-06-29 13:22 UTC, merged