[Hacktoberfest] Python | Non-Constructible Change
codeconnector/CodingDojo pull request #193
Opened 2021-10-01 21:11 UTC by williycole

# Language
Python

# Challenge
Non-Constructible Change

#Approach
TDD 

Closes #179

2021-10-01 21:52 UTC, xanderyzwich requested changes

2021-10-01 21:52 UTC, xanderyzwich commented on .gitignore
> +challenges/2021-05-11-nonconstructible-change/solutions/python/__pycache__/non_constructible_change.cpython-39.pyc
change this to **.pyc

2021-10-01 21:52 UTC, xanderyzwich commented on challenges/2021-05-11-nonconstructible-change/solutions/python/.gitignore
> +.xml
These can be added to the main gitignore with **/.xml and **/.idea (or similar)

2021-10-01 21:52 UTC, xanderyzwich commented on challenges/2021-05-11-nonconstructible-change/solutions/python/non_constructible_change_test.py
> +    unittest.main()
Python files by convention should have newline at the end of the file.

2021-10-04 13:45 UTC, xanderyzwich approved these changes

2021-10-04 13:46 UTC, parhaml approved these changes

2021-10-04 13:47 UTC, merged