Challenge setup for 2024-10-08 meetup
codeconnector/CodingDojo pull request #410
Opened 2024-10-01 01:33 UTC by ericwburden

# Language

C#

# Challenge

Name That Number

2024-10-06 15:18 UTC, mrumiker requested changes
Just a couple typos and suggestion for a few more tests.

2024-10-06 15:18 UTC, mrumiker commented on challenges/2024-10-08-name-that-number/challenge.md
> +User experience! At least, that's what your project manage told you when they introduced this user story. "As a user, I need to be able to read all numbers displayed in the application as English wor
```suggestion
User experience! At least, that's what your project manager told you when they introduced this user story. "As a user, I need to be able to read all numbers displayed in the application as English words without needing to translate them myself." Seems like a bit of unnecessary hand-holding to you, but all you get to vote on is how many story points this feature will be worth. Oh well, at least it's a good opportunity to practice your TDD on company time. For this task, you'll need to write a function that takes in a six-digit number and returns its string representation as English words. For example, `578119` becomes `"five hundred and seventy eight thousand one hundred and nineteen"`.
```

2024-10-06 15:18 UTC, mrumiker commented on challenges/2024-10-08-name-that-number/challenge.md
> +- NUmbers with at least four digits will include the word "thousand", for example `2861` as `"two thousand eight hundred and sixty one"`.
```suggestion
- Numbers with at least four digits will include the word "thousand", for example `2861` as `"two thousand eight hundred and sixty one"`.
```

2024-10-06 15:18 UTC, mrumiker commented on challenges/2024-10-08-name-that-number/challenge.md
Do we usually include instructions for running the tests?

2024-10-06 15:18 UTC, mrumiker commented on challenges/2024-10-08-name-that-number/NameThatNumber.cs
Tests look good, but let's add a test for 7000, 100000, and 999999. First two because we should make sure we're covering cases with lots of zeroes at the end, and the last one just to make sure we cover the full range of numbers.

2024-10-07 19:12 UTC, mrumiker approved these changes
Looks great!

2024-10-07 19:18 UTC, xanderyzwich approved these changes
LGTM

2024-10-07 19:18 UTC, merged