Laurelin wip
codeconnector/CodingDojo pull request #44
Opened 2021-04-20 19:17 UTC by Laurelin

The markdown was pretty Java-specific, so I'm really unsure about whether I did this correctly here. test is separate from the laurelin.py because that's how pytest works, afaik. I built this with python 3.8.5.

2021-04-20 19:21 UTC, parhaml commented on challenges/2021-04-20-potential-palindrome/solutions/laurelin.py
> +    if len([val for val, chr in freq.items() if chr % 2 != 0]) > 1:
nice oneliner

2021-04-20 20:11 UTC, ericwburden requested changes
This looks good! I like having the test file in here. (I've seen setups in Python with the tests and code in the same file, but it may not have been using pytest). The only change I'm requesting is that you remove the *.pyc (bytecode) files from the branch.

2021-04-20 22:19 UTC, drkennetz approved these changes

2021-04-20 22:19 UTC, drkennetz commented on challenges/2021-04-20-potential-palindrome/solutions/laurelin.py
> +    if len([val for val, chr in freq.items() if chr % 2 != 0]) > 1:
This is nice!

2021-04-20 23:02 UTC, Laurelin commented
Thanks! I think I've removed the bytecode parts.

2021-04-21 11:41 UTC, ericwburden approved these changes
Perfect!

2021-04-21 12:40 UTC, parhaml approved these changes

2021-04-21 12:40 UTC, parhaml commented
@Laurelin if you're ready. Will you remove `wip` from the PR title? Or let me know and I'll merge your solution. Great work! 💯

2021-04-21 14:15 UTC, drkennetz commented
@parhaml I took care of it!

2021-04-21 14:16 UTC, merged